{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "d78c8e45",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: fire_alarm.mp3\n",
      "Exception in thread Thread-5:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\darve\\AppData\\Local\\Temp\\ipykernel_18708\\3423033891.py\", line 13, in play_alarm_sound_function\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 72, in _playsoundWin\n",
      "    winCommand(u'open {}'.format(sound))\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Fire alarm initiated\n",
      "Capturing photo...\n",
      "Photo captured: incident_1693939892.jpg\n",
      "Sending message and photo...\n",
      "Fire alarm initiated\n",
      "Fire is already detected.\n",
      "Fire alarm initiated\n",
      "Fire is already detected.\n",
      "Fire alarm initiated\n",
      "Fire is already detected.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "    Error 259 for command:\n",
      "        play fire_alarm.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "Exception in thread Thread-9:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\darve\\AppData\\Local\\Temp\\ipykernel_18708\\3423033891.py\", line 13, in play_alarm_sound_function\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 73, in _playsoundWin\n",
      "    winCommand(u'play {}{}'.format(sound, ' wait' if block else ''))\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 259 for command:\n",
      "        play fire_alarm.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "\n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: fire_alarm.mp3\n",
      "Exception in thread Thread-10:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\darve\\AppData\\Local\\Temp\\ipykernel_18708\\3423033891.py\", line 13, in play_alarm_sound_function\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 72, in _playsoundWin\n",
      "    winCommand(u'open {}'.format(sound))\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: fire_alarm.mp3\n",
      "Exception in thread Thread-11:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\darve\\AppData\\Local\\Temp\\ipykernel_18708\\3423033891.py\", line 13, in play_alarm_sound_function\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 72, in _playsoundWin\n",
      "    winCommand(u'open {}'.format(sound))\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: fire_alarm.mp3\n",
      "Exception in thread Thread-12:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\darve\\AppData\\Local\\Temp\\ipykernel_18708\\3423033891.py\", line 13, in play_alarm_sound_function\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 72, in _playsoundWin\n",
      "    winCommand(u'open {}'.format(sound))\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Fire alarm initiated\n",
      "Fire is already detected.\n",
      "Fire alarm initiated\n",
      "Fire is already detected.\n",
      "Fire alarm initiated\n",
      "Fire is already detected.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: fire_alarm.mp3\n",
      "Exception in thread Thread-13:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\darve\\AppData\\Local\\Temp\\ipykernel_18708\\3423033891.py\", line 13, in play_alarm_sound_function\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 72, in _playsoundWin\n",
      "    winCommand(u'open {}'.format(sound))\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 259 for command:\n",
      "        play fire_alarm.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "Exception in thread Thread-14:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\darve\\AppData\\Local\\Temp\\ipykernel_18708\\3423033891.py\", line 13, in play_alarm_sound_function\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 73, in _playsoundWin\n",
      "    winCommand(u'play {}{}'.format(sound, ' wait' if block else ''))\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "\n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 259 for command:\n",
      "        play fire_alarm.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "Failed to close the file: fire_alarm.mp3\n",
      "Exception in thread Thread-15:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\darve\\AppData\\Local\\Temp\\ipykernel_18708\\3423033891.py\", line 13, in play_alarm_sound_function\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 72, in _playsoundWin\n",
      "    winCommand(u'open {}'.format(sound))\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Fire alarm initiated\n",
      "Fire is already detected.\n",
      "Fire alarm initiated\n",
      "Fire is already detected.\n",
      "Fire alarm initiated\n",
      "Fire is already detected.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: fire_alarm.mp3\n",
      "Exception in thread Thread-16:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\darve\\AppData\\Local\\Temp\\ipykernel_18708\\3423033891.py\", line 13, in play_alarm_sound_function\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 72, in _playsoundWin\n",
      "    winCommand(u'open {}'.format(sound))\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Fire alarm initiated\n",
      "Fire is already detected.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: fire_alarm.mp3\n",
      "Exception in thread Thread-17:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\darve\\AppData\\Local\\Temp\\ipykernel_18708\\3423033891.py\", line 13, in play_alarm_sound_function\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 72, in _playsoundWin\n",
      "    winCommand(u'open {}'.format(sound))\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 259 for command:\n",
      "        play fire_alarm.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "Exception in thread Thread-18:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\darve\\AppData\\Local\\Temp\\ipykernel_18708\\3423033891.py\", line 13, in play_alarm_sound_function\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 73, in _playsoundWin\n",
      "    winCommand(u'play {}{}'.format(sound, ' wait' if block else ''))\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 259 for command:\n",
      "        play fire_alarm.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "\n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: fire_alarm.mp3\n",
      "Exception in thread Thread-19:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\darve\\AppData\\Local\\Temp\\ipykernel_18708\\3423033891.py\", line 13, in play_alarm_sound_function\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 72, in _playsoundWin\n",
      "    winCommand(u'open {}'.format(sound))\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Fire alarm initiated\n",
      "Fire is already detected.\n",
      "Fire alarm initiated\n",
      "Fire is already detected.\n",
      "Fire alarm initiated\n",
      "Fire is already detected.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: fire_alarm.mp3\n",
      "Exception in thread Thread-21:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\darve\\AppData\\Local\\Temp\\ipykernel_18708\\3423033891.py\", line 13, in play_alarm_sound_function\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 72, in _playsoundWin\n",
      "    winCommand(u'open {}'.format(sound))\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: fire_alarm.mp3\n",
      "Exception in thread Thread-22:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\darve\\AppData\\Local\\Temp\\ipykernel_18708\\3423033891.py\", line 13, in play_alarm_sound_function\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 72, in _playsoundWin\n",
      "    winCommand(u'open {}'.format(sound))\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Fire alarm initiated\n",
      "Fire is already detected.\n",
      "Fire alarm initiated\n",
      "Fire is already detected.\n",
      "Fire alarm initiated\n",
      "Fire is already detected.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: fire_alarm.mp3\n",
      "Exception in thread Thread-23:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\darve\\AppData\\Local\\Temp\\ipykernel_18708\\3423033891.py\", line 13, in play_alarm_sound_function\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 72, in _playsoundWin\n",
      "    winCommand(u'open {}'.format(sound))\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 259 for command:\n",
      "        play fire_alarm.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "Exception in thread Thread-26:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\darve\\AppData\\Local\\Temp\\ipykernel_18708\\3423033891.py\", line 13, in play_alarm_sound_function\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 73, in _playsoundWin\n",
      "    winCommand(u'play {}{}'.format(sound, ' wait' if block else ''))\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 259 for command:\n",
      "        play fire_alarm.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "\n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: fire_alarm.mp3\n",
      "Exception in thread Thread-28:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\darve\\AppData\\Local\\Temp\\ipykernel_18708\\3423033891.py\", line 13, in play_alarm_sound_function\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 72, in _playsoundWin\n",
      "    winCommand(u'open {}'.format(sound))\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Fire alarm initiated\n",
      "Fire is already detected.\n",
      "Fire alarm initiated\n",
      "Fire is already detected.\n",
      "Fire alarm initiated\n",
      "Fire is already detected.\n",
      "Fire alarm initiated\n",
      "Fire is already detected.\n",
      "Fire alarm initiated\n",
      "Fire is already detected.\n",
      "Fire alarm initiated\n",
      "Fire is already detected.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: fire_alarm.mp3\n",
      "Exception in thread Thread-29:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\darve\\AppData\\Local\\Temp\\ipykernel_18708\\3423033891.py\", line 13, in play_alarm_sound_function\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 72, in _playsoundWin\n",
      "    winCommand(u'open {}'.format(sound))\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: fire_alarm.mp3\n",
      "Exception in thread Thread-30:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\darve\\AppData\\Local\\Temp\\ipykernel_18708\\3423033891.py\", line 13, in play_alarm_sound_function\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 72, in _playsoundWin\n",
      "    winCommand(u'open {}'.format(sound))\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: fire_alarm.mp3\n",
      "Exception in thread Thread-31:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\darve\\AppData\\Local\\Temp\\ipykernel_18708\\3423033891.py\", line 13, in play_alarm_sound_function\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 72, in _playsoundWin\n",
      "    winCommand(u'open {}'.format(sound))\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: fire_alarm.mp3\n",
      "Exception in thread Thread-32:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\darve\\AppData\\Local\\Temp\\ipykernel_18708\\3423033891.py\", line 13, in play_alarm_sound_function\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 72, in _playsoundWin\n",
      "    winCommand(u'open {}'.format(sound))\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Fire alarm initiated\n",
      "Fire is already detected.\n",
      "Fire alarm initiated\n",
      "Fire is already detected.\n",
      "Fire alarm initiated\n",
      "Fire is already detected.\n",
      "Fire alarm initiated\n",
      "Fire is already detected.\n",
      "Fire alarm initiated\n",
      "Fire is already detected.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: fire_alarm.mp3\n",
      "Exception in thread Thread-34:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\darve\\AppData\\Local\\Temp\\ipykernel_18708\\3423033891.py\", line 13, in play_alarm_sound_function\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 72, in _playsoundWin\n",
      "    winCommand(u'open {}'.format(sound))\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Fire alarm initiated\n",
      "Fire is already detected.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: fire_alarm.mp3\n",
      "Exception in thread Thread-35:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\darve\\AppData\\Local\\Temp\\ipykernel_18708\\3423033891.py\", line 13, in play_alarm_sound_function\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 72, in _playsoundWin\n",
      "    winCommand(u'open {}'.format(sound))\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: fire_alarm.mp3\n",
      "Exception in thread Thread-36:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\darve\\AppData\\Local\\Temp\\ipykernel_18708\\3423033891.py\", line 13, in play_alarm_sound_function\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 72, in _playsoundWin\n",
      "    winCommand(u'open {}'.format(sound))\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Fire alarm initiated\n",
      "Fire is already detected.\n",
      "Fire alarm initiated\n",
      "Fire is already detected.\n",
      "Fire alarm initiated\n",
      "Fire is already detected.\n",
      "Fire alarm initiated\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: fire_alarm.mp3\n",
      "Exception in thread Thread-38:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\darve\\AppData\\Local\\Temp\\ipykernel_18708\\3423033891.py\", line 13, in play_alarm_sound_function\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 72, in _playsoundWin\n",
      "    winCommand(u'open {}'.format(sound))\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: fire_alarm.mp3\n",
      "Exception in thread Thread-39:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\darve\\AppData\\Local\\Temp\\ipykernel_18708\\3423033891.py\", line 13, in play_alarm_sound_function\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 72, in _playsoundWin\n",
      "    winCommand(u'open {}'.format(sound))\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: fire_alarm.mp3\n",
      "Exception in thread Thread-40:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\darve\\AppData\\Local\\Temp\\ipykernel_18708\\3423033891.py\", line 13, in play_alarm_sound_function\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 72, in _playsoundWin\n",
      "    winCommand(u'open {}'.format(sound))\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 259 for command:\n",
      "        play fire_alarm.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: fire_alarm.mp3\n",
      "Exception in thread Thread-41:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\darve\\AppData\\Local\\Temp\\ipykernel_18708\\3423033891.py\", line 13, in play_alarm_sound_function\n",
      "\n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 73, in _playsoundWin\n",
      "\n",
      "    Error 263 for command:\n",
      "        close fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: fire_alarm.mp3\n",
      "    winCommand(u'play {}{}'.format(sound, ' wait' if block else ''))\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "Exception in thread Thread-42:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 259 for command:\n",
      "        play fire_alarm.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n",
      "    self.run()\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\darve\\AppData\\Local\\Temp\\ipykernel_18708\\3423033891.py\", line 13, in play_alarm_sound_function\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 72, in _playsoundWin\n",
      "    winCommand(u'open {}'.format(sound))\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: fire_alarm.mp3\n",
      "Exception in thread Thread-43:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\darve\\AppData\\Local\\Temp\\ipykernel_18708\\3423033891.py\", line 13, in play_alarm_sound_function\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 72, in _playsoundWin\n",
      "    winCommand(u'open {}'.format(sound))\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Fire is already detected.\n",
      "Fire alarm initiated\n",
      "Fire is already detected.\n",
      "Fire alarm initiated\n",
      "Fire is already detected.\n",
      "Fire alarm initiated\n",
      "Fire is already detected.\n",
      "Fire alarm initiated\n",
      "Fire is already detected.\n",
      "Fire alarm initiated\n",
      "Fire is already detected.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: fire_alarm.mp3\n",
      "Exception in thread Thread-44:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\darve\\AppData\\Local\\Temp\\ipykernel_18708\\3423033891.py\", line 13, in play_alarm_sound_function\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 72, in _playsoundWin\n",
      "    winCommand(u'open {}'.format(sound))\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: fire_alarm.mp3\n",
      "Exception in thread Thread-45:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\darve\\AppData\\Local\\Temp\\ipykernel_18708\\3423033891.py\", line 13, in play_alarm_sound_function\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 72, in _playsoundWin\n",
      "    winCommand(u'open {}'.format(sound))\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: fire_alarm.mp3\n",
      "Exception in thread Thread-46:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\darve\\AppData\\Local\\Temp\\ipykernel_18708\\3423033891.py\", line 13, in play_alarm_sound_function\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 72, in _playsoundWin\n",
      "    winCommand(u'open {}'.format(sound))\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "\n",
      "    Error 263 for command:\n",
      "        close fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: fire_alarm.mp3\n",
      "Exception in thread Thread-47:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\darve\\AppData\\Local\\Temp\\ipykernel_18708\\3423033891.py\", line 13, in play_alarm_sound_function\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 72, in _playsoundWin\n",
      "    winCommand(u'open {}'.format(sound))\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 263 for command:\n",
      "        open fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Fire alarm initiated\n",
      "Fire is already detected.\n",
      "Fire alarm initiated\n",
      "Fire is already detected.\n",
      "Fire alarm initiated\n",
      "Fire is already detected.\n",
      "Fire alarm initiated\n",
      "Fire is already detected.\n",
      "Fire alarm initiated\n",
      "Fire is already detected.\n",
      "Fire alarm initiated\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "    Error 259 for command:\n",
      "        play fire_alarm.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Fire is already detected.\n",
      "Fire alarm initiated\n",
      "Fire is already detected.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "    Error 263 for command:\n",
      "        close fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: fire_alarm.mp3\n",
      "Exception in thread Thread-50:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 973, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\threading.py\", line 910, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\darve\\AppData\\Local\\Temp\\ipykernel_18708\\3423033891.py\", line 13, in play_alarm_sound_function\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 73, in _playsoundWin\n",
      "    winCommand(u'play {}{}'.format(sound, ' wait' if block else ''))\n",
      "  File \"C:\\Users\\darve\\anaconda3\\lib\\site-packages\\playsound.py\", line 64, in winCommand\n",
      "    raise PlaysoundException(exceptionMessage)\n",
      "playsound.PlaysoundException: \n",
      "    Error 259 for command:\n",
      "        play fire_alarm.mp3 wait\n",
      "    The driver cannot recognize the specified command parameter.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'ok': True, 'result': {'message_id': 154, 'from': {'id': 6330654585, 'is_bot': True, 'first_name': 'Fire 🔥🔥 fire alert', 'username': 'Aaglgibot'}, 'chat': {'id': 1881893014, 'first_name': 'darvesh', 'type': 'private'}, 'date': 1693939900, 'photo': [{'file_id': 'AgACAgUAAxkDAAOaZPd4vEegBXxO2K7Ft0hVHl5FEVEAAkO4MRtyMMFXHi0w-FVyhQ4BAAMCAANzAAMwBA', 'file_unique_id': 'AQADQ7gxG3IwwVd4', 'file_size': 1426, 'width': 90, 'height': 67}, {'file_id': 'AgACAgUAAxkDAAOaZPd4vEegBXxO2K7Ft0hVHl5FEVEAAkO4MRtyMMFXHi0w-FVyhQ4BAAMCAANtAAMwBA', 'file_unique_id': 'AQADQ7gxG3IwwVdy', 'file_size': 15386, 'width': 320, 'height': 240}, {'file_id': 'AgACAgUAAxkDAAOaZPd4vEegBXxO2K7Ft0hVHl5FEVEAAkO4MRtyMMFXHi0w-FVyhQ4BAAMCAAN4AAMwBA', 'file_unique_id': 'AQADQ7gxG3IwwVd9', 'file_size': 47313, 'width': 640, 'height': 480}], 'caption': 'FIRE ALERT 🔥🔥🔥!!!'}}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "    Error 263 for command:\n",
      "        close fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: fire_alarm.mp3\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Fire alarm end\n",
      "Fire alarm end\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "    Error 263 for command:\n",
      "        close fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: fire_alarm.mp3\n",
      "\n",
      "    Error 263 for command:\n",
      "        close fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: fire_alarm.mp3\n",
      "\n",
      "    Error 263 for command:\n",
      "        close fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: fire_alarm.mp3\n",
      "\n",
      "    Error 263 for command:\n",
      "        close fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: fire_alarm.mp3\n",
      "\n",
      "    Error 263 for command:\n",
      "        close fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: fire_alarm.mp3\n",
      "\n",
      "    Error 263 for command:\n",
      "        close fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: fire_alarm.mp3\n",
      "\n",
      "    Error 263 for command:\n",
      "        close fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: fire_alarm.mp3\n",
      "\n",
      "    Error 263 for command:\n",
      "        close fire_alarm.mp3\n",
      "    The specified device is not open or is not recognized by MCI.\n",
      "Failed to close the file: fire_alarm.mp3\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Fire alarm end\n",
      "Fire alarm end\n",
      "Fire alarm end\n",
      "Fire alarm end\n",
      "Fire alarm end\n",
      "Fire alarm end\n",
      "Fire alarm end\n",
      "Fire alarm end\n"
     ]
    }
   ],
   "source": [
    "import requests\n",
    "import time\n",
    "import cv2\n",
    "import threading\n",
    "import playsound\n",
    "import smtplib\n",
    "\n",
    "fire_cascade = cv2.CascadeClassifier('fire_detection_cascade_model.xml')\n",
    "vid = cv2.VideoCapture(0)\n",
    "runOnce = False\n",
    "\n",
    "def play_alarm_sound_function():\n",
    "    playsound.playsound('fire_alarm.mp3', True)\n",
    "    delay = 2\n",
    "    time.sleep(delay)\n",
    "    print(\"Fire alarm end\")\n",
    "\n",
    "def send_msg_with_photo(text, photo_path):\n",
    "    token = \"6330654585:AAHkRI__7aEsm8N4tQpKcbRTDI9YWQlR6YI\"\n",
    "    chat_id = \"1881893014\"\n",
    "\n",
    "    # Upload the photo to Telegram using multipart/form-data\n",
    "    url = f\"https://api.telegram.org/bot6330654585:AAHkRI__7aEsm8N4tQpKcbRTDI9YWQlR6YI/sendPhoto\"\n",
    "    files = {'photo': open(photo_path, 'rb')}\n",
    "    data = {'chat_id': chat_id, 'caption': text}\n",
    "    response = requests.post(url, files=files, data=data)\n",
    "    print(response.json())\n",
    "\n",
    "while True:\n",
    "    Alarm_Status = False\n",
    "    ret, frame = vid.read()\n",
    "\n",
    "    if not ret or frame is None:\n",
    "        print(\"Failed to read frame from video source.\")\n",
    "        continue\n",
    "\n",
    "    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)\n",
    "    fire = fire_cascade.detectMultiScale(frame, 1.2, 5)\n",
    "\n",
    "    for (x, y, w, h) in fire:\n",
    "        cv2.rectangle(frame, (x-20, y-20), (x+w+20, y+h+20), (255, 0, 0), 2)\n",
    "        roi_gray = gray[y:y+h, x:x+w]\n",
    "        roi_color = frame[y:y+h, x:x+w]\n",
    "\n",
    "        print(\"Fire alarm initiated\")\n",
    "        threading.Thread(target=play_alarm_sound_function).start()\n",
    "\n",
    "        if runOnce is False:\n",
    "            print(\"Capturing photo...\")\n",
    "            timestamp = int(time.time())\n",
    "            photo_path = f\"incident_{timestamp}.jpg\"\n",
    "            cv2.imwrite(photo_path, frame)\n",
    "            print(\"Photo captured:\", photo_path)\n",
    "            \n",
    "            print(\"Sending message and photo...\")\n",
    "            threading.Thread(target=send_msg_with_photo, args=(\"FIRE ALERT 🔥🔥🔥!!!\", photo_path)).start()\n",
    "            runOnce = True\n",
    "        else:\n",
    "            print(\"Fire is already detected.\")\n",
    "\n",
    "    cv2.imshow('frame', frame)\n",
    "    if cv2.waitKey(1) & 0xFF == ord('q'):\n",
    "        break\n",
    "\n",
    "vid.release()\n",
    "cv2.destroyAllWindows()\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3c9c187d",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e51b9a27",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "f09f2edf",
   "metadata": {},
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f61dadd4",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d6b33bf0",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d83696c6",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0efd5eae",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2cbfba56",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "308ec363",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0d4f3f27",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ab3ede2f",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2d0b259f",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f6546198",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "106f142e",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
